name: HROne Attendance Bot

on:
    schedule:
        # Runs at 9:22 AM IST (Check In) - Monday to Friday
        - cron: "52 3 * * 1-5"

        # Runs at 9:56 PM IST (Check Out) - Monday to Friday
        - cron: "26 16 * * 1-5"

    # Allows you to run this manually from the Actions tab for testing
    workflow_dispatch:

jobs:
    mark-attendance:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install Dependencies
              run: |
                  pip install -r requirements.txt

            - name: Run Attendance Script
              env:
                  HRONE_URL: ${{ secrets.HRONE_URL}}
                  HRONE_USER: ${{ secrets.HRONE_USER }}
                  HRONE_PASS: ${{ secrets.HRONE_PASS }}
                  LATITUDE: ${{ secrets.LATITUDE }}
                  LONGITUDE: ${{ secrets.LONGITUDE }}
                  PYTHONUNBUFFERED: "1"
              run: python attendance_bot.py

            - name: Upload error screenshot
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: error-screenshot
                  path: error_*.png
                  if-no-files-found: ignore
